---
title: "Churchill Model Runs"
output: pdf_document
date: "2024-02-15"
---

# Load Packages
```{r}
rm(list = ls())

library(data.table)
library(ggplot2)
library(cowplot)
library(openair)
library(plotrix)
library(signal)
library(svMisc)
library(zoo)
library(stringr)
library(plyr)
library(dplyr)
library(lubridate)
library(RColorBrewer)
library(tidyr)
```
# Load DF's 
```{r}
h1 = fread('G:/My Drive/Permafrost Pathways/Towers/Churchill/Data/CA_CF3.csv', nrows = 1, skip = 0)
dat1 = fread('G:/My Drive/Permafrost Pathways/Towers/Churchill/Data/CA_CF3.csv',skip = 1, header = FALSE, na.strings=c('-9999','NA','NaN','NAN'))

h2 = fread('G:/My Drive/Permafrost Pathways/Towers/Churchill/Data/AMF_CA-CF2_BASE_HH_2-5.csv',nrows=1,skip=2)
dat2 = fread ('G:/My Drive/Permafrost Pathways/Towers/Churchill/Data/AMF_CA-CF2_BASE_HH_2-5.csv',skip = 3,header = FALSE, na.strings=c('-9999','NA','NaN','NAN'))

h3 = fread('G:/My Drive/Permafrost Pathways/Towers/Churchill/Data/AMF_CA-CF1_BASE_HH_2-5.csv',nrows=1,skip=2)
dat3 = fread ('G:/My Drive/Permafrost Pathways/Towers/Churchill/Data/AMF_CA-CF1_BASE_HH_2-5.csv',skip = 3,header = FALSE, na.strings=c('-9999','NA','NaN','NAN'))

names(dat1) = names(h1)
names(dat2) = names(h2)
names(dat3) = names(h3)

CF3= dat1
CF2 = dat2
CF1 = dat3
```

# Timestamps
```{r}

#CF2

CF2$ts = as.character(CF2$TIMESTAMP_START)

CF2$year = substr(CF2$ts,1,4)
CF2$month = substr(CF2$ts,5,6)
CF2$day = substr(CF2$ts,7,8)
CF2$hour = substr(CF2$ts,9,10)
CF2$min = substr(CF2$ts,11,12)



CF2$ts = as.POSIXct(paste(CF2$year,CF2$month,CF2$day,CF2$hour,CF2$min,sep = ''),
                    format = '%Y%m%d%H%M',
                    tz = "America/Belize"	
                    )

CF2$date = as.POSIXct(paste(CF2$year,CF2$month,CF2$day,sep = ''),
                      format = '%Y%m%d')
#CF1

CF1$ts = as.character(CF1$TIMESTAMP_START)

CF1$year = substr(CF1$ts,1,4)
CF1$month = substr(CF1$ts,5,6)
CF1$day = substr(CF1$ts,7,8)
CF1$hour = substr(CF1$ts,9,10)
CF1$min = substr(CF1$ts,11,12)



CF1$ts = as.POSIXct(paste(CF1$year,CF1$month,CF1$day,CF1$hour,CF1$min,sep = ''),
                    format = '%Y%m%d%H%M',
                    tz = "America/Belize"	
                    )

CF1$date = as.POSIXct(paste(CF1$year,CF1$month,CF1$day,sep = ''),
                      format = '%Y%m%d')

#CF3

CF3$ts = as.character(CF3$TIMESTAMP_START)

CF3$year = substr(CF3$ts,1,4)
CF3$month = substr(CF3$ts,5,6)
CF3$day = substr(CF3$ts,7,8)
CF3$hour = substr(CF3$ts,9,10)
CF3$min = substr(CF3$ts,11,12)



CF3$ts = as.POSIXct(paste(CF3$year,CF3$month,CF3$day,CF3$hour,CF3$min,sep = ''),
                    format = '%Y%m%d%H%M',
                    tz = "America/Belize"	
                    )


CF3$date = as.POSIXct(paste(CF3$year,CF3$month,CF3$day,sep = ''),
                      format = '%Y%m%d')


```

## Variable names CF3
```{r,warning = FALSE}

#Removing TS_1_1_1, TS_2_1_1, and TS_2_2_1 (choosing to use therm data, not CS655's)
#Changing TS_3 and TS_4 into TS_2 and TS_1 
#Changing TS_2_1_1 and TS_2_2_1 into TS_3_0_1 & TS_3_05_1

CF3 <- CF3 %>% select(-TS_1_1_1)
CF3 <- CF3 %>% select(-TS_2_1_1)
CF3 <- CF3 %>% select(-TS_2_2_1)


#Open water therms
names(CF3)[names(CF3) == "TS_3_1_1"] <- "TS_2_0_1"
names(CF3)[names(CF3) == "TS_3_2_1"] <- "TS_2_05_1"
names(CF3)[names(CF3) == "TS_3_3_1"] <- "TS_2_1_1"
names(CF3)[names(CF3) == "TS_3_4_1"] <- "TS_2_2_1"
names(CF3)[names(CF3) == "TS_3_5_1"] <- "TS_2_3_1"
names(CF3)[names(CF3) == "TS_3_6_1"] <- "TS_2_4_1"
names(CF3)[names(CF3) == "TS_3_7_1"] <- "TS_2_5_1"
names(CF3)[names(CF3) == "TS_3_8_1"] <- "TS_2_6_1"
names(CF3)[names(CF3) == "TS_3_9_1"] <- "TS_2_7_1"
names(CF3)[names(CF3) == "TS_3_10_1"] <- "TS_2_8_1"
names(CF3)[names(CF3) == "TS_3_11_1"] <- "TS_2_9_1"
names(CF3)[names(CF3) == "TS_3_12_1"] <- "TS_2_10_1"

names(CF3)[names(CF3) == "TS_4_1_1"] <- "TS_1_0_1"
names(CF3)[names(CF3) == "TS_4_2_1"] <- "TS_1_05_1"
names(CF3)[names(CF3) == "TS_4_3_1"] <- "TS_1_1_1"
names(CF3)[names(CF3) == "TS_4_4_1"] <- "TS_1_2_1"
names(CF3)[names(CF3) == "TS_4_5_1"] <- "TS_1_3_1"
names(CF3)[names(CF3) == "TS_4_6_1"] <- "TS_1_4_1"
names(CF3)[names(CF3) == "TS_4_7_1"] <- "TS_1_5_1"
names(CF3)[names(CF3) == "TS_4_8_1"] <- "TS_1_6_1"
names(CF3)[names(CF3) == "TS_4_9_1"] <- "TS_1_7_1"
names(CF3)[names(CF3) == "TS_4_10_1"] <- "TS_1_8_1"
names(CF3)[names(CF3) == "TS_4_11_1"] <- "TS_1_9_1"
names(CF3)[names(CF3) == "TS_4_12_1"] <- "TS_1_10_1"


```
## Merge
```{r}

#Merge
merged_df = rbind.fill(CF1,CF2,CF3)

merged_df$DOY = yday(merged_df$date)

merged_df$year = substr(merged_df$date,1,4)


```

# Daily Average
```{r}

avg = timeAverage(
  merged_df,
  avg.time = 'day',
  data.thresh = 40,
  statistic = 'mean',
  fill = TRUE
)


df = timeAverage(
  CF3,
  avg.time = 'day',
  data.thresh = 40,
  statistic = 'mean',
  fill = TRUE
)


```
## time separations 
```{r}
avg$year = substr(avg$date,1,4)
avg$year <- factor(avg$year)

avg$DOY = yday(avg$date)
avg$DOY <- as.numeric(avg$DOY)

df$year = substr(df$date,1,4)
df$year <- factor(df$year)

df$DOY = yday(df$date)
df$DOY <- as.numeric(df$DOY)

df$month = as.numeric(format(df$ts,'%m'))
```
# Graphs
## multi-year annual plot (rough)
```{r,warning = FALSE}

ggplot(data = avg)+theme_bw()+
  geom_point(aes(DOY,FCH4,color = year))+
  geom_hline(yintercept = 0)+
  scale_x_continuous(limits = c(110,340))+
  scale_y_continuous (expression('CH4 Flux ('*n*mol~m^-2~s^-1*')'),
                      limits = c(-10,150))+
  labs(color='Year')
```
# 
```{r}

ggplot(data = df)+theme_bw()+
  geom_point(aes(date,FCH4))+
  geom_line(aes(x = ts, y = TS_2_05_1*4), color = 'blue') + 
  geom_hline(yintercept = 0)+
  scale_y_continuous (expression('CH4 Flux ('*n*mol~m^-2~s^-1*')'),
                      limits = c(-30,140),
  sec.axis = sec_axis(~./4, name = "Soil Temperature 10cm (°C)")
  ) 


```






## 5,10 cm Hysteresis 
### Blue
```{r}

ggplot(data = df)+theme_bw()+
  geom_point(aes(x = TS_2_1_1, y = FCH4, fill = DOY),pch=21,size = 3,alpha=0.75) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
                     limits = c(-10, 150)) +
  scale_x_continuous(expression('Temperature 10 cm(°C)'),
                     limits = c(-15,17))+
  labs(color = 'DOY')+
#  scale_fill_brewer(palette = 'YlOrRd')
  scale_fill_gradientn(colours = brewer.pal(9,'GnBu'))


ggplot(data = df)+theme_bw()+
  geom_point(aes(x = TS_2_05_1, y = FCH4, fill = DOY),pch=21,size = 3,alpha=0.75) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
                     limits = c(-10, 150)) +
  scale_x_continuous(expression('Temperature 5 cm(°C)'),
                     limits = c(-15,18))+
  labs(color = 'DOY')+
#  scale_fill_brewer(palette = 'YlOrRd')
  scale_fill_gradientn(colours = brewer.pal(9,'GnBu'))
```
### Red
```{r}
ggplot(data = df)+theme_bw()+
  geom_point(aes(x = TS_2_1_1, y = FCH4, fill = month),pch=21,size = 3,alpha=0.75) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
                     limits = c(-30, 150)) +
  scale_x_continuous(expression('Temperature 10cm(°C)'),
                     limits = c(-15,15))+
  labs(color = 'DOY')+
#  scale_fill_brewer(palette = 'YlOrRd')
  scale_fill_gradientn(colours = brewer.pal(9,'Reds'))

```
## Soil T CH4 Timeseries
```{r}


ggplot(data = df) +
  theme_bw() +
  geom_point(aes(x = ts, y = FCH4), color = 'salmon') +
  geom_line(aes(x = ts, y = TS_2_05_1*4), color = 'blue') +  
  geom_hline(yintercept = 0) +
  scale_y_continuous(
    name = expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
    limits = c(-20, 95),
    sec.axis = sec_axis(~./4, name = "Soil Temperature 5cm (°C)")
  ) +
  scale_x_datetime(limits = as.POSIXct(c('2023-04-16', '2023-12-23')))


ggplot(data = df) +
  theme_bw() +
  geom_point(aes(x = ts, y = FCH4), color = 'salmon') +
  #geom_line(aes(x = ts, y = TS_2_05_1*4), color = 'blue') +  
  geom_hline(yintercept = 0) +
  scale_y_continuous(
    name = expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
    limits = c(-20, 95),
    #sec.axis = sec_axis(~./4, name = "Soil Temperature 10cm (°C)")
  ) +
  scale_x_datetime(limits = as.POSIXct(c('2023-04-16', '2023-12-23')))

ggplot(data = CF3) +
  theme_bw() +
  geom_point(aes(x = ts, y = FCH4), color = 'salmon') +
  #geom_line(aes(x = ts, y = TS_2_05_1*4), color = 'blue') +  
  geom_hline(yintercept = 0) +
  scale_y_continuous(
    name = expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
    limits = c(-50, 95),
    sec.axis = sec_axis(~./4, name = "Soil Temperature 10cm (°C)")
  ) +
  scale_x_datetime(limits = as.POSIXct(c('2023-09-16', '2023-12-23')))
```
# Model Runs
## LM Runs 0, 5, 10 cm
```{r}
#0 cm (R-squared 0.73)
TS0logCH4 = lm(log10(FCH4+5)~TS_1_0_1,data = df)
summary((TS0logCH4))


#5cm (R-squared 0.76)
TS5logCH4 = lm(log10(FCH4+5)~TS_2_05_1,data = df)
summary((TS5logCH4))

#5cm (R-squared 0.72)
TS10logCH4 = lm(log10(FCH4+5)~TS_2_1_1,data = df)
summary((TS10logCH4))

```
## Trendline 5 cm
```{r}
# Define the exponential trend function
exponential_trend_5 <- function(x) {
  10^(1.155294 + 0.050221 * x) - 5
}

# Determine the number of rows in your original dataframe df
num_rows_df <- nrow(df)

# Create the new dataframe with the same number of rows as df, removing NA values
new_data <- data.frame(TS_2_05_1 = seq(min(na.omit(df$TS_2_05_1)), max(na.omit(df$TS_2_05_1)), length.out = num_rows_df))
new_data$predicted <- exponential_trend_5(new_data$TS_2_05_1)


ggplot(data = df) +
  theme_bw() +
  geom_point(aes(x = TS_2_05_1, y = FCH4, fill = month), pch = 21, size = 3, alpha = 0.75) +
  geom_hline(yintercept = 0) +
  geom_point(aes(x = TS_2_05_1, y = exponential_trend_5(TS_2_05_1)), color = "black", size = 1.3) +
  scale_y_continuous(expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
                     limits = c(-8, 150)) +
  scale_x_continuous(expression('Temperature 5 cm (°C)'),
                     limits = c(-15, 20)) +
  labs(color = 'DOY') +
  scale_fill_gradientn(colours = brewer.pal(9, 'Reds'))

ggplot(data = new_data) +
  theme_bw() +
  geom_line(aes(x = TS_2_05_1), alpha = 0.5, fill = "blue") +
  scale_y_continuous(expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'),
                     limits = c(-8, 150)) +
  scale_x_continuous(expression('Temperature 5 cm (°C)'),
                     limits = range(new_data$TS_2_05_1)) +  # Adjust x-axis limits
  labs(color = 'DOY') +
  theme(legend.position = "none")
min(df$FCH4,na.rm = TRUE)
```
## LM 5 model
```{r}

# Extract the predicted log10(FCH4 + 5) values from the model
predicted_FCH4 <- predict(TS5logCH4)

# Exponentiate the predicted log10(FCH4 + 5) values to obtain predicted FCH4 values
p_FCH4 <- 10^predicted_FCH4 - 5

df$p_FCH4 = p_FCH4

# Plot the predicted FCH4 values against the actual FCH4 values
plot(p_FCH4, pch = 16, col = "blue", xlab = "Actual FCH4", ylab = "Predicted FCH4", main = "Predicted vs Actual FCH4")
abline(0, 1, col = "red")  # Add a reference line with slope 1 and intercept 0 for comparison



# Extract the subset of observations used for fitting the model
df_subset <- df[!is.na(df$TS_2_05_1), ]

# Predict CH4 values for the subset of observations
predicted_FCH4_subset <- 10^predict(TS5logCH4, newdata = df_subset) - 5

# Add the predicted CH4 values to your dataframe df_subset
df_subset$Predicted_CH4 <- predicted_FCH4_subset

# Merge the predicted CH4 values back to the original dataframe df
df <- merge(df, df_subset[, c("ts", "Predicted_CH4")], by = "ts", all.x = TRUE)

# Check the structure of your dataframe to confirm that the new column has been added
str(df)


plot(df$FCH4,df$Predicted_CH4)


ggplot(data = df) +
  theme_bw() +
  geom_point(aes(x = ts, y = FCH4, color = "Observed CH4"), alpha = 0.5) +
  geom_point(aes(x = ts, y = Predicted_CH4, color = "Predicted CH4"), alpha = 0.5) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(expression('CH4 Flux (' * n * mol ~ m^-2 ~ s^-1 * ')'), limits = c(-6, 135)) +
  scale_x_datetime(limits = as.POSIXct(c('2022-08-6', '2023-12-31'))) +
  labs(color = "CH4 Values") +
  scale_color_manual(values = c("Observed CH4" = "salmon", "Predicted CH4" = "blue")) +
  guides(color = guide_legend(title = "CH4 Values"))

```




## LM Runs GPP
```{r}
#GPP_DT (R-squared 0.66)
GPP_DTCH4 = lm(FCH4~GPP_DT,data = df)
summary((GPP_DTCH4))

#GPP_F (R-squared 0.76) (feels sketch using this bc gap-filled)
GPP_FCH4 = lm(FCH4~GPP_F,data = df)
summary((GPP_FCH4))



```


## Time lag 
```{r}
#Rain
ccf(df$P,df$FCH4, na.action = na.pass)
#Soil T
ccf(df$TS_2_05_1,df$FCH4, na.action = na.pass)
#VWC
ccf(df$SWC_2_1_1,df$FCH4, na.action = na.pass)
#GPP
ccf(df$GPP_F,df$FCH4, na.action = na.pass)



```

## Seasons breakdown
```{r}
ggplot(data = df) +
  theme_bw() +
  geom_point(aes(x = ts, y = PPFD_IN), color = 'salmon') +
  geom_point(aes(x = ts, y = PPFD_OUT), color = 'blue') +
  geom_hline(yintercept = 0) +
  scale_y_continuous(
    name = expression('PPFD (' * PAR * ')'),
    limits = c(-20, 795),
    #sec.axis = sec_axis(~./4, name = "Soil Temperature 10cm (°C)")
  ) +
  scale_x_datetime(limits = as.POSIXct(c('2022-08-6', '2023-12-31')))

albedo = df$PPFD_OUT/df$PPFD_IN

plot(df$ts,albedo)
ALB = albedo
ALB = ifelse(albedo > 1 ,NA,ALB)
plot(ALB)

ts = df$ts

ggplot ()+
  theme_bw() +
  geom_point(aes(x = ts, y = albedo), color = 'red') +
  geom_point(aes(x = ts, y = ALB), color = 'black') +
  geom_hline(yintercept = 0) +
  scale_y_continuous(
    name = expression('ALBEDO (' * PAR * ')'),
    limits = c(-.1, 1.25),
    #sec.axis = sec_axis(~./4, name = "Soil Temperature 10cm (°C)")
  ) +
  scale_x_datetime(limits = as.POSIXct(c('2023-10-28', '2023-11-1')))
```




# Raster Column 
format is |Date|SoilT|SoilDepth|
```{r}

dfnew = df
dfnew$TS_2_0_1 = dfnew$TS_2_05_1


ras <- dfnew[,c('date',
            'TS_2_0_1', 
            'TS_2_1_1', 
            'TS_2_2_1', 
            'TS_2_3_1',
            'TS_2_4_1',
            'TS_2_5_1', 
            'TS_2_6_1', 
            'TS_2_7_1', 
            'TS_2_8_1',
            'TS_2_9_1')]


# Reshape the data into long format
ras <- ras %>%
  pivot_longer(
    cols = -date, 
    names_to = "SoilDepth",
    values_to = "SoilTemperature",
    names_pattern = "TS_2_(\\d+)_1" 
  ) %>%
  mutate(SoilDepth = as.numeric(gsub("TS_2_", "", SoilDepth)) * 10) 

# Extract Date from column
ras$date <- as.Date(ras$date)

# Select and reorder columns
ras <- ras %>%
  select(date, SoilDepth, SoilTemperature)

library(viridis)

ggplot(ras, aes(x = date, y = SoilDepth, fill = SoilTemperature)) +
  geom_raster()+
  scale_fill_viridis(option = "turbo") +  # Use the "magma" color palette
  labs(x = "Date", y = "Soil Depth", fill = "Soil Temperature") +
  scale_y_reverse() +  # Invert the y-axis
  theme_minimal()
  
```











